name: Release
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_SECRET }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@trust0'  # Replace with your organization scope
          cache: 'npm'
          cache-dependency-path: ./ts/package-lock.json

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./ts/.npmrc
          echo "@trust0:registry=https://registry.npmjs.org/" >> ./ts/.npmrc
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}

      - name: Run semantic-release
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
        run: cd ts && npm ci && npx semantic-release
